### ISSUE TITLE
Question: Is this project still being maintained?

### ISSUE THREAD

**Issue by fearphage** [jsforce/jsforce#1064]
There are almost 50 pull requests (dating back as far as 2016) and over 300 unaddressed unresolved issues. The tests don't even run consistently in the pull requests. The tests are failing in master. The last release was in December of last year.

I'm wondering if this project is still in active development or has it been abandoned? Are you looking for other maintainers to take over?

**Comment by lms15** [comment]
No I have not idea how to stop this I thought my account was deleted How do I delete this account cannot log in to Github
Mamie
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by lms15** [comment]
No thought it was deleted? Help me delete cannot login to github

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Codeneos** [comment]
I share your concerns!

This is one of the most used libraries for interacting with Salesforce, even SFDX (@salesforce/core package) uses this for Salesforce connectivity.

Before last week I didn't really monitor this repository but I am an active user of jsforce but I noticed a bug and decided to open  PR addressing the issue - but instead of a meaningful response I get spam from @lms15. After which I started to investigate the other open PRs, issues and branch history. It looks unmaintained to say the least - which for such an important project in the Salesforce ecosystem is worrying.

@jsforce are you considering putting this repository up for adoption or at-least getting more maintainers on board?

**Comment by stomita** [comment]
As the lead author of this repository, I apologize for the delay in responding to the numerous issues and pull requests.

As previously mentioned in #889, this repository is currently in the process of migrating to code that has been rewritten in TypeScript (the code is being developed in branch 2.0). This makes it difficult to add features to the current master code. This should have been stated in the README or something like that, but it was unclear to new users of this repository.

The transition to TypeScript in 2.0 is a bit more complicated, partly because I've introduced several ideas at the same time. Additionally, it's taking a bit longer due to code at work and other OSS projects I'm involved with.

Currently, 2.0 is still in the alpha version, but the core functionality is mostly implemented and I personally think it's ready to be used in the product code (in fact, my company has started using JSforce 2.0 for product development).

My current goal is to have an official release by the end of this year, but unfortunately I can't guarantee that until it's up and running on a volunteer basis. Anyway, I will tell you that, that development of JSforce is continuing.

**Comment by lms15** [comment]
Can I delete this?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by RaviVaranasi** [comment]
How do the types get generated if it is a lookup vs master-detail relationship? If we want to get types for a lookup item, then what are the options?

**Comment by s0up2up** [comment]
@stomita - Do you have an ETA for jsforce 2.0?

**Comment by mannharleen** [comment]
@stomita - Is there somewhere a list of breaking changes to APIs from 1.0 to 2.0?

**Comment by cristiand391** [comment]
ref: https://github.com/jsforce/jsforce/issues/1360
