### ISSUE TITLE
Cannot use allowRecursive in typescript

### ISSUE THREAD

**Issue by jonathanwiesel** [jsforce/jsforce#1068]
According to the [docs](https://jsforce.github.io/document/#operation-options) you can use the `allowRecursive` flag to let jsforce automatically process recursively more than 200 records

```
conn.sobject('Account')
  .create(
    accounts,
    { allowRecursive: true },
    function(err, rets) {
      if (err) { return console.error(err); }
      console.log('processed: ' + rets.length);
    }
  );
```

However, this doesn't seem to be available in the [typescript definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jsforce/connection.d.ts).

Possibly related to #1005 since that other option seems to be unavailable too.

**Comment by paustint** [comment]
@jonathanwiesel 
The typescript definitions are not maintained by the core team and are provided by the community on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/jsforce). You will need to open a ticket there, or even better, submit a PR on that repo to get the change made.

jsforce version 2.0 is written in Typescript and is being slowly worked on and might be released coming years, at which time we should have native type definitions:
https://github.com/jsforce/jsforce/issues/889
https://github.com/jsforce/jsforce/tree/2.0 (branch with new codebase)

In my opinion, this ticket should probably be closed since the type definition is not part of this repository.

**Comment by jonathanwiesel** [comment]
Thank you @paustint just submitted the pull request, hope someone can approve it soon (noticed there are some related issues to this use case)

DefinitelyTyped/DefinitelyTyped/pull/48101

**Comment by jonathanwiesel** [comment]
Contribution in DefinitelyTyped has been merged, so this can be closed
