### ISSUE TITLE
Replacing `request`

### ISSUE THREAD

**Issue by amphro** [jsforce/jsforce#1136]
This thread is to start a discussion on a `request` replacement in [v2](https://github.com/jsforce/jsforce/issues/1137).

There are a lot of articles around replacements, top HTTP libraries, etc. I have found this [chart](https://github.com/sindresorhus/got#comparison) the most useful.

My first preference is `got`. It says it doesn't support browsers but I think browserify that is already set up in jsforce should take care of that I have not confirmed this.

My second preference is `axios`. Although not as many features, it is well supported. My biggest problem is that the version has been <1 for over 5 years.

**Comment by amphro** [comment]
Based on what @paustint said about `got`, I agree it isn't a great leading choice. I'm fine with `axios`.

I will leave this thread open for a weak or two to give any others in the community a chance to voice their opinion. @stomita do you have an opinion?

**Comment by jimmywarting** [comment]
I would be fine with whatever http library that uses fetch as the underlying ajax method instead of XMLHttpRequest

XMLHttpRequest don't work in web workers...
https://stackoverflow.com/questions/67584416/migrating-to-service-worker-xhr-to-fetch

I would vote for fetch and node-fetch
fetch has the advantage of being Streamable

**Comment by amphro** [comment]
The v2 branch still has request in the node_module but I noticed node_fetch is already brought in, and Shinichi already replaced it in #1090 so we are good hear. I'll close this out.
