### ISSUE TITLE
jsforce get records from custom object

### ISSUE THREAD

**Issue by rikyo233** [jsforce/jsforce#1162]
Help~~~

I used the Salesforce REST API to get record data. 
For a standard object (user), I can get all records in one request, but for a custom object, I can only get 200, 250, 500, or 1000 records in one request. (The number of records that can be get differs depending on the object)

```
conn.login( oauth_client_username, oauth_client_authenticate_password, function(err, res) {
    if (err) { return console.error(err); }
    conn.sobject("custom object").select('*').limit(20000).execute(function(err,records){
      if (err) { return console.error(err); }
      console.log(records.length);
    });
})
```

**Comment by paustint** [comment]
Salesforce will ALWAYS paginate data depending on how expensive the request is. Since you are getting all fields, depending on the type of fields will change what Salesforce deems expensive. Including a subquery will be even more expensive.

Salesforce will return a maximum of 2000 records and as few as 1 record in one response. You need to use the query locator provided in the response along with queryMore() to paginate until you have all the records.

Alternatively you can use the bulk api, but keep in mind that some fields/query features (compound fields such as Billing address and subqueries) are not supported.

**Comment by rikyo233** [comment]
@paustint 
Thank you for you help.
I used the `autoFetch` in `execute` and I can get all records already.

`.execute({autoFetch: true, maxFetch: 100000},function(err,records)`
