### ISSUE TITLE
Question: After acquiring the access and refresh tokens, can't do anything useful with them.

### ISSUE THREAD

**Issue by stdarg** [jsforce/jsforce#1167]
After placing the refresh token, access token and the instance URL in the session, I have the following code:

```javascript
  app.get('/api/v1/refresh', function (req, res) {
    const conn = new jsforce.Connection({
      oauth2: {
        clientId: process.env.SALESFORCE_CONSUMER_ID,
        clientSecret: process.env.SALESFORCE_CONSUMER_SECRET,
        redirectUri: process.env.SALESFORCE_CALLBACK_URL
      },
      instanceUrl: req.session.user.salesforce.instanceUrl,
      accessToken: req.session.user.salesforce.accessToken,
      refreshToken: req.session.user.salesforce.refreshToken
    })

    conn.oauth2.refreshToken(req.session.user.refreshToken, (err, results) => {
      if (err) {
        return res.json({ error: err.message })
      }
      res.json(results)
    })
  })
```

I know jsforce will automatically exchange an expired access token when a valid refresh token is supplied, here, I'm just trying to see the API work with the tokens. However, I get an error, "invalid_grant: expired access/refresh token".

Using `conn.sobject`, `conn.query` or `conn.search` results in no callback being called.

The scopes I specified for the app are:

- API
- profile
- web
- refresh_token, offline_access

Any insights on what I am doing wrong?

**Comment by paustint** [comment]
@stdarg - Here are some possible troubleshooting steps:
- You could try including the version in your connection, I have experienced random issues without it ` new jsforce.Connection({..., version: '52.0'})`
- Do a sanity check and make sure that the access token and refresh token from your session are indeed the most recent values that you got after authenticating
- Debug/console.log and copy the access token/refresh token and see if you can calll those directly (e.x. make a new js file and run just that file with the values hard-coded and try using conn.query to make sure that is working)

> Using conn.sobject, conn.query or conn.search results in no callback being called.

Do you have the same results if you use promises instead of callbacks? You could try using promises and see if an exception is thrown with more information as opposed to the callback not being called.
e.x. `await conn.query('SELECT Id FROM Account')`

**Comment by stdarg** [comment]
@paustint That was helpful, thank you. I can now see some unexpected behavior is that jsforce gets a 401 against the SF API and keeps trying endlessly without reporting an error.

**Comment by stdarg** [comment]
I'm going to close this issue and open another with a repro case.
