### ISSUE TITLE
Unable to login into sandbox with ServerURL

### ISSUE THREAD

**Issue by vinaykumar612** [jsforce/jsforce#1192]
**Not able login into sfdc sandbox using serverURL and SessionID**

```js
let conn=new jsforce.Connection({
    serverUrl : "https://*********/my.salesforce.com",
    sessionId : '************************',
});
await conn.login(username,password);
```
Getting INVALID_LOGIN: Invalid username, password, security token; or user locked out.

**Comment by madhavmaddy** [comment]
try this url: it's working for sandbox loginUrl: "https://test.salesforce.com/

**Comment by musmanfaisal** [comment]
Hi, I recently ran into this problem and turned out, while I made a sandbox environment, Salesforce made a testing account for me as well and appended .testing in the end

So for example my email is `test@example.com`, on sandbox, I had to log in with `test@example.com.testing`

Took me a while to get to it

So I just added a SALEFORCE_SANDBOX environment variable

```
await conn.login(
    process.env.SALEFORCE_USERNAME +
      (process.env.SALEFORCE_SANDBOX == "1" ? ".testingbox" : ""),
    process.env.SALEFORCE_PASSWORD
  );
```
