### ISSUE TITLE
🚨 `conn.metadata.read()` doesn't support 'ApexClass', 'ApexTrigger', and 'ApexTestSuite'

### ISSUE THREAD

**Issue by jmsfez** [jsforce/jsforce#1206]
Hi,
When considering the 'ApexClass' metadata type, I observed the following:
• `conn.metadata.describe()` returns the 'ApexClass' as a correct org's metadata type.
• `conn.metadata.list([{ type: 'ApexClass', folder: null }])` returns the correct collection of existing Apex class (with `fullNames`).
However...
• `conn.metadata.read('ApexClass', ['AnyApexClassFullName'])` always throws the following exception
    **INVALID_TYPE: This type of metadata is not available for this organization**

Notice that I observed exactly the same issue with the **'ApexTrigger'** and **'ApexTestSuite'** metadata types.
Is it a known issue?
Thank in advance for your help

**Comment by paustint** [comment]
Just tried this out and had the same experience you are reporting. This is a Salesforce limitation and not a limitation of jsforce.

Unfortunately the metadata API has some rough edges and looks like you found one! You might have better luck using the file-based version of the metadata api or use the tooling api.

The file based is annoying because you have to submit the request and then poll for the results.
The tooling based api is annoying because if you include the `FullName` or `Metadata` properties in a tooling query, then you can only have 1 record returned (salesforce limit).

I ended up abandoning `metadata.read()` when building https://getjetstream.app/ and use the file-based or tooling based approaches. (Jetstream is free and has some pretty cool tools for exploring and querying metadata that you will probably find useful)

I have found good luck using the tooling composite api to get around the 1 record limitation:
https://developer.salesforce.com/docs/atlas.en-us.api_tooling.meta/api_tooling/tooling_resources_composite_sobjects_collections.htm

But this also means you will want to use the generic request methods which are not documented well - but you can find some good information here. https://github.com/jsforce/jsforce/issues/934#issuecomment-546714813

**Comment by jmsfez** [comment]
Thank you for your responsiveness @paustint.
You've right, I replaced calls to `conn.metadata.read(metadataType, [metadataFullName])` by calls to `conn.tooling.sobject(metadataType).find({ Name: metadataFullName })` and it works fine 😉
