### ISSUE TITLE
Getting refresh token having issues

### ISSUE THREAD

**Issue by jaagaard01** [jsforce/jsforce#1210]
Hey was hoping for some help regarding getting my refresh token to work properly. Im doing a check to make sure my connections to sandboxes are still valid, my app currently connects multiple instances together. After about 24 hours thought the check im doing always fails with `invalid_grant: expired access/refresh token` 

```
   const conn = new jsforce.Connection({
        oauth2: {
          loginUrl: determineLoginUrl(),  (if sandbox this is test.salesforce.com)
          clientId: consumerKey,
          clientSecret: consumerSecret,
          redirectUri: dynamicRedirectUrl(), (this is for either local dev or production)
        },
        instanceUrl,
        accessToken: fetchedAccessToken,
        version: salesforceAPIVersion,
        refreshToken: fetchedRefreshToken,
      })
      console.log(conn, 'connection')
      conn.query(queryString, (err) => {
        console.log(err, 'errorr here')
        if (err) {
          res.status(200).send('Error')
        } else {
          res.status(200).send('Success')
        }
      })
    } catch (error) {
      res.status(200).send('Error')
    }
```

we store the tokens we create upon creating the original connection but after we have these envs setup we do checks to make sure the connection is still valid. Any help would be greatly appreciated!

**Comment by jaagaard01** [comment]
I was under in the impression if valid refresh token that even with expired access token the conn.query would still work. Do i need to add the one of the refresh flows? This connection is originally setup using oauth

**Comment by paustint** [comment]
From my experience the refresh token flow works no matter if your access token is expired. You should check out all your code paths where you are storing and using the refresh token to make sure that the refresh token used never changes for a user. (e.x. make sure your persistence and retrieval from persistence don't have any bugs)

Also, make sure you have the `refresh_token` scope included in your connected app (as a default or specified during auth flow) otherwise you won't get a refresh token to begin with.

One easy way to test is by invalidating your access token by deleting your `AuthSession` records
e.x. `delete [SELECT Id, UsersId FROM AuthSession]` (add where clause for the exact user you are testing with if needed)

that will force the access token to be invalid so that you can debug the next query request to investigate.

If you are using `conn.on('refresh', (accessToken, res) => {});` beware that `res` is undefined and that you need to keep your existing refreshToken as you are not given a new one. You only get a new accessToken.

If you are not using `conn.on('refresh',` and you are often re-initializing the connection on your server then you probably need to listen to this even and persist the refreshed access token, otherwise every single request the user makes will always require the refresh flow which takes additional network requests for each operation.

**Comment by jaagaard01** [comment]
thanks for this info @paustint, if I have already made a sf connection when the user first connects that sf instance to the app, should I not be doing a new jsforce connection? or would you think I would need to still do that but then do the `conn.on('refresh', (accessToken, res) => {});` and put my conn.query inside of that?

**Comment by jaagaard01** [comment]
im not currently using doing any conn.on or conn.oauth2.refreshToken

**Comment by jaagaard01** [comment]
do you happen to know if i need to refresh the access token before i run conn.query? if so, would i need to make the connection do a conn.on refresh and then make a new connection with the updated access token then follow that with the conn.query?

**Comment by paustint** [comment]
@jaagaard01 

>thanks for this info @paustint, if I have already made a sf connection when the user first connects that sf instance to the app, should I not be doing a new jsforce connection? or would you think I would need to still do that but then do the conn.on('refresh', (accessToken, res) => {}); and put my conn.query inside of that?

It is up to you if you want to create a new connection or re-use an instance.
If multiple users are interacting with your server at the same time, then they will each need their own instance for sure.
But for any individual user, it is up to you if you use one `conn` or a new one each time - it depends on how your application is structured and what your usage patterns are etc..

`conn.on('refresh', (accessToken, res) => {});` is an event the will fire if and only if the access token was expired and a new one was obtained automatically behind these scenes - in which case you might want to store the access token in your DB for future use. the jsforce instance automatically gets the new access token so you don't need to do anything.

You will not call this directly and it may never be called, so you will only put code in that to save the new accessToken in your DB, since you are saving the tokens.

>do you happen to know if i need to refresh the access token before i run conn.query? if so, would i need to make the connection do a conn.on refresh and then make a new connection with the updated access token then follow that with the conn.query?

No, you should never need to refresh the token yourself, this should all be handled transparently.

The refresh flow should just work, and if it isn't that means that you are initializing jsforce with an invalid refresh token or your conected app / authorization flow are not setup to correctly support using refresh tokens.
