### ISSUE TITLE
Bulk Upsert errors intermittently with {"name":"ClientInputError","errorCode":"ClientInputError"}

### ISSUE THREAD

**Issue by ramprasathb-accelerize360** [jsforce/jsforce#1216]
Logic used  for bulk upsert
`conn.bulk.pollTimeout = 50000;
      conn.bulk.load(
        objectName,
        'upsert',
        { extIdField: externalId },
        data,
        (error, results) => {
          if (error) {
            console.log(
              "Error in SF Bulk Push :: " + JSON.stringify(error)
            );
            resolve({ status: StringConstants.ERROR, error });
          }
          if (!isUndefined(results) && !isNull(results)) {
            resolve({ status: StringConstants.SUCCESS, results });
          } else {
            resolve({ status: StringConstants.PENDING, results });
          }
        }
      );`
conn => SF Connection object

For the above program, we are  intermittently facing an error which prints 
Error in SF Bulk Push :: {"name":"ClientInputError","errorCode":"ClientInputError"}

The error is not very detailed and **if we process the same set of records again (without changing anything in the dataset), the bulk upsert happens without any issues.**

Any suggestions on how to fix this?

**Comment by vinaykumar612** [comment]
Please mention the jsforce version.

**Comment by cristiand391** [comment]
triaging old issues...

`ClientInputError` could be because of a bad payload, see:
https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/asynch_api_reference_errors.htm?q=ClientInputError

the code uses callbacks so it's jsforce v1.

Please re-open if you can repro on jsforce v3 **and** with a consistent repro. If it's intermittent I would suggest logging the payload before creating the bulk operation.
