### ISSUE TITLE
Can we get request url or name in the debug logging?

### ISSUE THREAD

**Issue by dustinsmith1024** [jsforce/jsforce#1280]
It would be great to get some kind of name or URL in the request debug logging. I am trying to aggregate the metrics for each call we make to SalesForce and its a bit difficult when they are on separate log statements.

https://github.com/jsforce/jsforce/blob/888edd0ff29d9b4926b16ee5bdacb9b99e773fb8/lib/http-api.js#L82-L85

Also thought about just passing the timing information to the `emit` function and I could log appropriately there. However we are in lambda function and not sure how well waiting for async event would work out. It would probably be fine.

Just a thought. If I get some time I will try to PR.

**Comment by cristiand391** [comment]
jsforce v1 does log the request URL:
https://github.com/jsforce/jsforce/blob/888edd0ff29d9b4926b16ee5bdacb9b99e773fb8/lib/http-api.js#L79

> I am trying to aggregate the metrics for each call we make to SalesForce and its a bit difficult when they are on separate log statements

not sure how exactly this is done but you could try filtering by logs starting with `<request>`.

Regarding events, you probably won't be able to listen to these events because methods don't expose the internal `HttpApi` instance.
