### ISSUE TITLE
[usage question] is .execute() necessary when using promises instead of callbacks?

### ISSUE THREAD

**Issue by techieshark** [jsforce/jsforce#1351]
Hi, first off thanks for this great library!

The following is just a question, not a bug report. Please let me know if there's a better forum for these.

Does anyone know if the `.execute()` call is required in the example below?

I'm wondering if I can take this code:

```
                    const [first_result] = await connection
                        .sobject('Contact')
                        .find(
                            // conditions:
                            { Id: contactID },
                            // fields:
                            basicContactFields
                        ).execute(); // NOTE THIS LINE IS THE ONLY DIFFERENCE
```

and remove the `.execute()` call, like so:

```
                    const [first_result] = await connection
                        .sobject('Contact')
                        .find(
                            // conditions:
                            { Id: contactID },
                            // fields:
                            basicContactFields
                        );
```

I've reviewed the guides and API docs but if anyone but it's possible I missed something. Would very much appreciate any explanation of the importance of `.execute()` in this context. 

Thanks all

**Comment by cristiand391** [comment]
this is doc'd here:
https://jsforce.github.io/document/#query

most query/crud methods return a `Query` instance that extends `EventEmitter`:
https://jsforce.github.io/jsforce/classes/query.Query.html

for the even-driven style where you listen on `record` events you need to call `execute` at the end of the chain (note that `run`/`exec` are aliases for `execute`:
https://jsforce.github.io/document/#query

when `await`ing on it like in the examples you don't need to call `execute` because it's done internally on the `then` method:
https://jsforce.github.io/jsforce/classes/query.Query.html#then
https://github.com/jsforce/jsforce/blob/52aeb9a935b8495edbf432efb2b0c1df3b365f30/src/query.ts#L868
