### ISSUE TITLE
Metadata API DeployResult: missing properties?

### ISSUE THREAD

**Issue by hansnieuwenhuis** [jsforce/jsforce#144]
I'm trying to use Metadata#deploy in order to deploy `scr.zip` with the following:

``` javascript
var jsforce = require('jsforce');
var express = require('express');
var fs = require('fs');
var stringifyobject = require('stringify-object');

var app = express();

app.set('port', (process.env.PORT || 5000));

app.get('/', function(request, response) {

    //...
    // sfConnection.login happens here
    //...

    var zipStream = fs.createReadStream("./src.zip");

    sfConnection.metadata.deploy(zipStream).complete(function(err, result) {
        if (err) { console.error(err); }
        console.log('result: ' + stringifyobject(result));
    });
});

app.listen(app.get('port'), function() {
  console.log("Node app is running at localhost:" + app.get('port'))
});
```

There is an (intentional) error in my `src.zip`, when I look at the `result` object, I can see `status: 'Failed'`, but I would also expect errorStatusCode and errorMessage to appear and have a value?

**Comment by cristiand391** [comment]
triaging old issues...

jsforce returns the result from the server so that would be the API missing those fields.
Per API docs, they aren't optional so it could be your specific intentional error at the time.
https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_deployresult.htm
