### ISSUE TITLE
Which MongoDB-like features are supported?

### ISSUE THREAD

**Issue by fourq** [jsforce/jsforce#172]
I'd like to know what mongo syntax I can use. Like is $regex supported? A list would be great.

**Comment by stomita** [comment]
The operator `$regex` is not supported right now because SOQL doesn't have the equivalent.
Currently `$ne`, `$lt`, `$lte`, `$gt`, `$gte`, `$in`, `$nin`, and `$exists` are supported.
Additionally `$like` and `$nlike`, which are not available in original mongo query operators, mapped to `field LIKE value` and `NOT (field LIKE value)`.
