### ISSUE TITLE
bulk api lookup field cannot manipulate with external id

### ISSUE THREAD

**Issue by jinceon** [jsforce/jsforce#207]
{
   extid__r : { code__c : 'afafa'}
}

sobject().upsert works well.
but sobject().upsertBulk failed. It seems like it ignores the reference field.

**Comment by stomita** [comment]
JSforce is not currently supporting bulk upsert with relationship via Bulk API.

**Comment by desheng-xu** [comment]
I have the same issue and My solution is query the reference field id first.by the way, will it supported In the next version?

**Comment by clems71** [comment]
Would be really great!

**Comment by bvellacott** [comment]
Any news on this one? Surely this should work by now

**Comment by srajagopalan1712** [comment]
@jinceon @bvellacott Do either of you have a sample code to upsert with parent external id for regular sobject api, not bulk. I am trying to understand how to code that using jsforce. Thx.

**Comment by jon-freed** [comment]
As you're using JSforce, and as you're setting up your CSV, be sure to set your column header values so that you can do this kind of lookup to an external id.  For details and an example, see the Bulk API Developer Guide, [Relationship Fields in a Header Row](https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/datafiles_csv_rel_field_header_row.htm)

**Comment by taylordowns2000** [comment]
@aleksa-krolls, I've had success using the CSV header row specification _in_ JSForce. (Maybe this is what @jon-freed means above?) Your record array looks like this:

```js
[
  {
    Project_Series__c: line.ProjectSeries,
    Staff_Code__c: line.StaffCode,
    'Budget__r.Name': line.BudgetCode, // 'relationshipName__r.externalIDField'
  },
  { ... },
  ...
]
```
