### ISSUE TITLE
Weird and unexpected PollingTimeout error

### ISSUE THREAD

**Issue by green2k** [jsforce/jsforce#237]
Hi guys, 

I have some weird problem with fetching results from bulk query (createBulk, updateBulk, ...). Sometimes, (about once, twice in a week), we get a PollingTimeout error. We've increased polling timeout from 10000ms to 20000ms, but this doesn't solve it. 

The problem is, that (as you can see - http://prntscr.com/7psiru) the API returns PollingTimeout error. But when I look into a salesforce job result (http://prntscr.com/7psl1v), I see that the job was successfully completed in 3122ms and with 0 retries :-(. 

Does anyone have the same problem, or some hint about how to resolve it? 

I'll be very thankful

**Comment by ivolo** [comment]
I'm having a similar issue. Salesforce shows that the problem is completed under a second: 

![image](https://cloud.githubusercontent.com/assets/658544/8686171/bef3c692-2a38-11e5-80b6-a98d3080963a.png)

and it times out:

![image](https://cloud.githubusercontent.com/assets/658544/8686180/d06de60a-2a38-11e5-8eb2-4a3a012d5b75.png)

I'm using the `.load` buik API call:

```js
var res = yield conn.bulk.load('Account', 'update', accounts);
```

It might be the failing of a single poll call (I'm at a coffee shop), retries may be useful or better logging about what the intermediate poll responses were before the batch timeout is called.

**Comment by ivolo** [comment]
Haha, that was just the internet in the cafe, polling is consistent and correct in a place with solid internet. Disregard me!
