### ISSUE TITLE
Streaming CSV Parser

### ISSUE THREAD

**Issue by ivolo** [jsforce/jsforce#249]
Is there a plan to support streaming csv bulk queries to lessen impact on memory when the result set is more than a few hundred megabytes? 

It looks like the [current code](https://github.com/jsforce/jsforce/blob/master/lib/record-stream.js#L251) is downloading the entire CSV into memory, parsing it, and then emitting `record` events.

**Comment by stomita** [comment]
Definitely there is a plan but not in milestone yet.

**Comment by tejasmanohar** [comment]
I'm also interested in this enhancement. Either [csv-parse](https://github.com/wdavidw/node-csv-parse) or [fast-csv](https://github.com/C2FO/fast-csv) should do the trick.

**Comment by bdmayes** [comment]
I'm confused about this. Are you saying that the code shown at https://jsforce.github.io/document/#bulk-api isn't actually creating a stream? Specifically, this is the code I'm referring to:

```
var fs = require('fs');
conn.bulk.query("SELECT Id, Name, NumberOfEmployees FROM Account")
  .stream().pipe(fs.createWriteStream('./accounts.csv'));
```

If it's not a true stream, then how is it being piped into a writable stream? Or are you only talking about a parser after the fact, as in reading the CSV after it exists on disk?

I'm extremely curious because I was thinking of making my own Writable that would buffer up some of the events and then copy them to S3 before moving on to the next chunk of records. Something like this (not fully-implemented, promise-y, pseudo-code):

```
var buffer = [];

var Writable = require('stream').Writable;
var ws = Writable();
ws._write = function (chunk, enc, next) {
    buffer.push(chunk);

    if (buffer.length === 5000) {
        copyToS3(buffer, function(err, data) {
            buffer = [];
            next();
        });
    } else {
        next();
    }
};

conn.bulk.query("SELECT Id, Name, NumberOfEmployees FROM Account")
  .stream().pipe(ws);
```


Obviously there would be other edge cases to handle and so on. But if you already have a CSV file, I think you should look at a different parsing library as jsforce is really meant for interactions with Salesforce, not an all-in-one CSV parser. Or am I missing something?

**Comment by tejasmanohar** [comment]
@bdmayes Not using JSForce for streaming bulk query results anymore / at the moment, but from my understanding, the CSV from the API response is stored in full *in-memory*, not buffered "on disk" as you've mentioned. The CSV is parsed synchronously [here](https://github.com/jsforce/jsforce/blob/master/lib/record-stream.js#L251) when the response is consumed. Implementing the stream interface doesn't guarantee that the operations used to produce the data that's pushed onto the stream are async :)

**Comment by bdmayes** [comment]
That is extremely unfortunate. I guess the current "stream" implementation is only a facade that implements methods of the same name of streams? I need to look around the code more I suppose. In that case, I am also very interested in this enhancement.

@tejasmanohar Did you find another library? We have historically been using nforce to issue SOQL queries via the REST API, but I have found a few use-cases where an object has so many custom fields with long names, that the HTTP GET request fails via the REST API. Using the Bulk API works for such long queries, but if this is buffering all records in memory then it is probably not a feasible solution at the moment.

**Comment by tejasmanohar** [comment]
@bdmayes It is a node stream, but it takes synchronous operations (e.g. CSV parsing) to build the data that's pushed onto the stream. I'm using my own thing atm w/ fast-csv. I use JSForce for normal API calls and to create the Bulk Job (as I don't want to touch the SOAP API), but then I use an in-house, adhoc solution to actually stream the results down and parse them. It's not well decoupled atm, but the end goal should be to send a PR to JSForce that switches out the current CSV parser for a streaming one-- I probably won't get to it for a bit since I'm using less and less of the lib but wouldn't mind reviewing/testing one.

**Comment by bdmayes** [comment]
Thanks for the clarification. I guess for now I'm going to look at implementing this by manually logging in, creating jobs/batches, and polling. This would definitely be a useful utility however and I hope it makes it in by the currently assigned 1.7.0 milestone. :)

**Comment by tejasmanohar** [comment]
@bdmayes You can implement everything but streaming the CSV down using JSForce without any memory issues. It's just the CSV parsing that needs to be made streaming (or done separately).

**Comment by bdmayes** [comment]
Understood. I'll stop polluting this request any further at this point...but yes, my plan was to leverage jsforce to handle the icky SOAP interaction to login, and just use its methods for submitting jobs and batches and so on. Only the actual retrieval of data from the query would change.

**Comment by stomita** [comment]
@bdmayes I'd like to clarify the current (1.6) JSforce behavior for better understanding.

- `Bulk#query()` returns a `RecordStream` instance - a special Node.js stream which emits record object.
- The `RecordStream` instance in `Bulk#query()` parses CSV response from API **only when it has direct stream consumers**.
- `RecordStream#stream()` returns a raw readable CSV data stream - actually it is HTTP response body of API request. If you pipe them to another writable stream, it will not consume any intermediate disk space or memory (excluding for buffering).

As @tejasmanohar pointed out, the parser used in bulk query is currently a synchronous one - it stores all CSV body in memory for parsing. The CSV parser will become stream-based one in next release.

**Comment by bdmayes** [comment]
Thanks @stomita. I am actually more interested in a direct stream case, not resulting in a CSV file. I'll settle for a CSV if I absolutely have to and then parse it from disk, but it's not my first choice. Instead, I would prefer to to do something similar to what I outlined above, resulting in JSON. Then I can buffer up N number of JSON records into a single file, compress it/upload it to S3, and finally write some metadata about that file to our database.

It sounds like you're saying that I should be able to invoke conn.bulk.query() and since that returns a RecordStream instance, I should be able to pipe that into any Writable stream instance that I want? Unfortunately I'll have to do the parsing of it to find beginning/end of records on my own (or maybe I can set object mode on the stream to save me some effort?). I'll have to dive deeper into your parsing implementation to see if I can learn a thing or two. :)

If that's the case then I think you're saying that something like my previous code snippet should work because it's directly consuming the RecordStream emitted by Bulk#query(), and therefore not running through the CSVStreamConverter. Is that an accurate statement?

**Comment by tejasmanohar** [comment]
The results come back in a CSV format, and the parser would parse them into objects as they come in (easily JSON stringifiable).

**Comment by bdmayes** [comment]
Thanks guys. I'm just tackling this problem as I have a free week at work this week and it is an issue that has bugged me for a while (and something that more and more of our customers are starting to hit for a handful of object types). Doesn't have to be resolved right away however as we have been living with it for a while already.

But I definitely see that calling stream() on the ResultStream will fall into the CsvStreamConvertor.parse() function which hits the problematic parsing code. For now I'll just stream it out to a CSV file on disk using the existing parser (oh well), then parse that file on my own. This will allow me to get _something_ working, and have most of the necessary code scaffolding in place. When 1.7 comes out, I can hopefully update to that, tweak a few things, and be all set to do it in a single pass (without ever loading the entire thing into memory).

I really appreciate all of the info.
