### ISSUE TITLE
Bulk load API only uploads fields from first object

### ISSUE THREAD

**Issue by danlash** [jsforce/jsforce#258]
The bulk loader seems to be extracting the fields from the first object only. Example:

```
var accounts = [
  { Name: 'Account A', OwnerId: 'xxx', Industry: 'Insurance'}, 
  { Name: 'Account B', OwnerId: 'xxx' }
];
conn.bulk.load("Account", "insert", accounts, function(err, res) {
  console.log(err, res)
});
```

Account A and B are created just fine with all fields specified being set. However, if the order is switched:

```
var accounts = [
  { Name: 'Account C', OwnerId: 'xxx' },
  { Name: 'Account D', OwnerId: 'xxx', Industry: 'Insurance'}
];
conn.bulk.load("Account", "insert", accounts, function(err, res) {
  console.log(err, res)
});
```

Account C and D are created, but D does not have the Industry field set.

I dug into the code a bit but it looks like the CSV#extractHeaders is doing the right thing.

**Comment by rsievekndy** [comment]
I am also finding this issue exactly as @danlash has described.

**Comment by stomita** [comment]
This is the expected behavior. The bulk loader only scans first record in the input to create CSV header list currently. This is because we need to keep all records in memory in order to have exactly correct headers. To support stream uploading, we assume the first record contains all field properties which are also available in following records.
