### ISSUE TITLE
Custom CSV parser & formatter

### ISSUE THREAD

**Issue by tejasmanohar** [jsforce/jsforce#425]
Is there a reason JSForce has its [own CSV parser/formatter](https://github.com/jsforce/jsforce/blob/master/lib/csv.js) rather than using an existing one like [fast-csv](https://www.npmjs.com/package/fast-csv) or [csv-parse](https://www.npmjs.com/package/csv-parse)? Are there any custom, Salesforce-specific transformations in this parser?

PS: I'm currently not using it because the usage of the CSV parser in JSForce waits for all records to be returned and then parses the CSV rather than doing it in a streaming-fashion, which takes up too much memory for large data sets, but I've been having some trouble with some records coming back from the Bulk Query API with generic csv parsers so wondering if there are any quirks of the CSV returned from SF that you've noticed. @stomita

**Comment by stomita** [comment]
Actually the historical reason. At that time we couldn't find the satisfying CSV parser lib in npm so implemented it (I remember some parser has a problem during dealing with CJK text). I'm not sure if fast-csv resolves the problem or not but worth to try.

> JSForce waits for all records to be returned and then parses the CSV rather than doing it in a streaming-fashion, 

Yes, this is true, and this is also why we selected to implement our own CSV parser instead of using existing parsers (at that time there was no good streaming parsers I could find), but we didn't have a time to fully implement it. Now it seems the fast-csv has the feature so we might think of it.

**Comment by stomita** [comment]
As you may know the raw CSV text response of bulk query can be obtained in stream by `bulk.query(soql).stream()`, which will bypass the built-in CSV parser.

```js
conn.bulk.query('SELECT Id, Name FROM Account')
  .stream()
  .pipe(fs.createWriteStream('./accounts.csv'));
```

**Comment by tejasmanohar** [comment]
> Actually the historical reason

Ah, I see. Makes sense.

>Now it seems the fast-csv has the feature so we might think of it.

To clarify, does this mean you're considering using fast-csv as a streaming parser or synchronous parser after all the data is already in memory like JSForce does now? I'd suggest using its streaming parser.

>As you may know the raw CSV text response of bulk query can be obtained in stream by bulk.query(soql).stream(), which will bypass the built-in CSV parser.

I actually did not know that. I'll migrate my code over to this. Thanks!
