### ISSUE TITLE
bulk.load function does not create multiple batches when more than 10000 records in input

### ISSUE THREAD

**Issue by TonyWhiteSMS** [jsforce/jsforce#469]
It would seem that the bulk.load function - https://jsforce.github.io/jsforce/doc/Bulk.html#load
Does not create batches from the input data, once the first 10,000 records are processed it finishes... and the first batch appears to have an error on the 10,001 record...

The code I implemented is the same as defined here - https://jsforce.github.io/document/#load-from-records except the object is a custom object and the action is an upsert.

**Comment by stomita** [comment]
Importing more than 10,000 records in a `load()` call is not supported currently. This is because one batch request has [a limitation of max 10,000 records](https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/asynch_api_concepts_limits.htm), and the `load()` call is only creating one job with one batch instance. If you need it now, try creating batch instances manually by `createBatch()` as described in the doc.

**Comment by moulicvr** [comment]
use LIMIT *** OFFSET ****

**Comment by moulicvr** [comment]
maybe you should try with  PK Chunk size approach.
