### ISSUE TITLE
Using Federated Authentication with jsForce

### ISSUE THREAD

**Issue by scromie** [jsforce/jsforce#521]
Hello,

I would like to be able to send a SAML assertion to SFDC and receive a token to get a session Id.  Is this possible with jsForce?  If so, please show a sample that would allow it to work.

In addition, if there is any way to do a REST passthrough, where I build the POST and jsForce sends it on and passes back the response, that could work for me too.

Also, SSO is definitely working as I can login to the identity provider and go directly to salesforce.

Thanks in advance!

Scott

**Comment by stomita** [comment]
You mean [0Auth2 SAML bearer assertion flow](https://help.salesforce.com/apex/HTViewHelpDoc?id=remoteaccess_oauth_SAML_bearer_flow.htm&language=en) ? If so, you can simply pass the SAML assertion to the token endpoint to fetch access token and instance url, and pass them to JSforce's `Connection` constructor options.

**Comment by scromie** [comment]
Thank you very much for your response!  I think we solved the problem -we are generating a SAML assertion within our node app and sending it to SFDC, and we are indeed getting a token and instance url.

Thanks again for the help!

Scott

**Comment by danscrima** [comment]
@scromie @stomita 
Would you be able to provide some quick guidance into how you are generating the SAML assertion? I have things working if I generate it through that Axiom interface and then using that assertion, but since its only valid quickly I can't use it again, which is why I assume you're generating a new one. 

I guess the flow is then to make a POST <somewhere> to generation the SAML assertion, then use that SAML assertion to post to the services/oauth2/token endpoint to give you the access_token and instance_url which you can then use moving forward from your app... Any help is appreciated, thanks!

**Comment by marrakchim** [comment]
@scromie Hello
I am trying to implement a SAML Bearer Assertion Flow within my app, same as you. Could you please give me more detail about how you generated the SAML Assertion within you node app ? I can't seem to be able to get my SAMLResponse after a successful authentication (I can see it on the Chrome Inspect but I can't get it on my Nodejs app). 
Thanks !
