### ISSUE TITLE
Is it possible to use SF Session Id to instantiate connection from static resource?

### ISSUE THREAD

**Issue by richykandora** [jsforce/jsforce#588]
I'm passing a session id into a js static resource file (static resource is being included onto a VF page) and trying to create a connection (and upload metadata) like so: 

                      var conn = new jsforce.Connection({ accessToken: sessionId });

			conn.metadata.create('ApexPage', files, function(err, results) {
				if (err) { console.log(err); }
				for (var i=0; i < results.length; i++) {
					var result = results[i];
					console.log('success ? : ' + result.success);
					console.log('fullName : ' + result.fullName);
				}
			});`

Yet I'm getting this error `Error: INVALID_SESSION_ID: Invalid Session ID found in SessionHeader: Illegal Session1`

Can you access the metadata API from a static resource using the session? If not, is there any way around this?

**Comment by cwheikki** [comment]
I think you'll want to utilize the ```sessionId``` option rather than ```accessToken``` when making your connection. You'll also need to provide the ```serverUrl``` option.

Documentation: https://jsforce.github.io/document/#session-id

Here is a code snippet that I have utilized to create the connection from a VF page. In your scenario you'll have to pass these values into your static resource.
```
var conn = new jsforce.Connection({
  serverUrl : '{!$Api.Partner_Server_URL_140}',
  sessionId : '{!$Api.Session_ID}'
});
```
Cheers,
Chris

**Comment by richykandora** [comment]
Ah, never mind, I screwed up. `accessToken` works fine
