### ISSUE TITLE
Ver 2.0 : Moving to the Modern Architecture (ES2015+)

### ISSUE THREAD

**Issue by stomita** [jsforce/jsforce#593]
As the current JSforce is written in ES5, the maintenance is becoming a little difficult as it cannot fully utilize the modern JavaScript ecosystem.

### The goals
- Modernize JavaScript coding, based on ES2015+ (ES6+), using babel.
- Move to webpack2 for building browser bundles (to reduce the minified size).
- Fix the interface to be type friendly. Overloading or dynamic type change should be reduced if it is unnecessary.
- As far as above goals are accomplished, leave the current interface to be unchanged.

### Things I'm not sure it should be introduced or not
- Flowtype

This can be injected afterward.

### Things I don't think to be introduced
- TypeScript

I decided to choose ES2015+, which is widely accepted now and has broader adoption than TS. When static type check is required there is Flow. However, it is OK to have a type definition outside of the project, and it would be much easier than today.

**Comment by chrisjlee** [comment]
There a branch you have work on currently? I can start working on this.

**Comment by paustint** [comment]
I have a request that may fit into a refactor to es6 and I completely understand if it is unreasonable.

Because the SFDC API is not 100% supported by this library, it would be good to have the ability to have a way to easily either:
1. The ability to add/modify headers and query parameters for all requests so we can take advantage of the SFDC API without being as limited by the library on a few edge-cases that aren't directly supported by the api.  **One simple example: For the query API, we should have the option to interact with all the query parameters - being able to use the `explain` param. This would require that the "q" parameter be nulled out as well in this case.**
1. Ability to retrieve all returned header information from any given API call
1. extend functionality by adding simple prototypes to classes. This would require a structure that uses a very standard way of calling apis. This may be unreasonable, but would be nice.

I am not sure if this is even the right place to suggest a change like this, but wanted to throw it out there to hear others opinions.
