### ISSUE TITLE
Chatter @mention support

### ISSUE THREAD

**Issue by kamilsmuga** [jsforce/jsforce#625]
Does jsforce have support for @mentioning people in Chatter?

**Comment by kamilsmuga** [comment]
@stomita

**Comment by paustint** [comment]
My guess is that this should be supported because it is just a message segment that includes the specified user data.
When posting a chatter message, you construct the message segment to include the "mention" object as a segment. You as an implementer of the SFDC API, you will have to parse out @username and put this into a segment, as the Salesforce API does not directly support @username to mention, but requires the data to be broken out into a segment.

Looking at the chatter code in the library, it is generic/universal and does not offer any extra data transformations to automate message segments - https://jsforce.github.io/jsforce/doc/Chatter-Resource.html#create

You will include a message segment as follows (use the user id or username in the segment):
```
conn.chatter.resource('/feed-elements').create({
  body: {
    messageSegments: [{
      type: 'Text',
      text: 'This is new post'
    },{
      type: 'Mention',
      id: 'sfdcUserIdHere'
    },{
      type: 'Mention',
      username: 'usernameHere'
    }]
  },
  feedElementType : 'FeedItem',
  subjectId: 'me'
}, function(err, result) {
  if (err) { return console.error(err); }
  console.log("Id: " + result.id);
  console.log("URL: " + result.url);
  console.log("Body: " + result.body.messageSegments[0].text);
  console.log("Comments URL: " + result.capabilities.comments.page.currentPageUrl);
});
```

https://developer.salesforce.com/docs/atlas.en-us.chatterapi.meta/chatterapi/connect_requests_message_body_input.htm

https://developer.salesforce.com/docs/atlas.en-us.chatterapi.meta/chatterapi/connect_requests_msg_seg_input_mention.htm

**Comment by kamilsmuga** [comment]
Worked like a charm! @paustint thank you!
@stomita great job on making the code generic!
