### ISSUE TITLE
refreshToken = undefined

### ISSUE THREAD

**Issue by alekhyaAppsbrew** [jsforce/jsforce#629]
I am  able to access all the details except refreshToken,though I am specifying the scope.

jsforce.browser.init({
	                clientId: '.............. ',
			redirectUri: 'http://localhost:8000/callback',
			proxyUrl: 'https://safe-stream-17926.herokuapp.com/proxy/',
			scope: 'chatter_api custom_permissions full id openid refresh_token visualforce web',
			grant_type:'refresh_token'
		});

Please guide me on the same

**Comment by paustint** [comment]
Do you have the scope configured in SFDC on your connected app?
"Perform requests on your behalf at any time (refresh_token, offline_access)"

Here is my scope and I am getting the refresh token: `scope: 'api full id web refresh_token'`

Also, I had to change my login to use the OAuth2 flow in order to get the refresh token, this appears to be available in the browser, but is not documented. https://github.com/jsforce/jsforce/blob/master/lib/browser/client.js

You will likely need to use a different login method and not init. My guess would be that init does not provide the needed stuff for the token refresh.

Here is my server side code (express)
This redirects to the login page, then upon the response the refresh token is provided - it was not using the other login methods shown in the example docs.
```
jsforce.OAuth2({
    loginUrl : loginUrl || 'https://login.salesforce.com',
    clientId : process.env.clientId,
    clientSecret : process.env.clientSecret,
    redirectUri : process.env.redirectUri
  }).getAuthorizationUrl({
    scope: 'api full id web refresh_token',
    state,
    prompt: 'login'
  }));
```


Looking at the source, the init calls to a "get tokens" function that ignores the refresh token (could be more things I am unaware of).  First, see if you can inspect `localStorage` to see what data is being stored in the browser and see if the refresh token exists there.  If the refresh token is not included, then you for sure need to use a different authentication method.

```
Client.prototype._getTokens = function() {
  var regexp = new RegExp("(^|;\\s*)"+this._prefix+"_loggedin=true(;|$)");
  if (document.cookie.match(regexp)) {
    var issuedAt = Number(localStorage.getItem(this._prefix+'_issued_at'));
    if (Date.now() < issuedAt + 2 * 60 * 60 * 1000) { // 2 hours
      var userInfo;
      var idUrl = localStorage.getItem(this._prefix + '_id');
      if (idUrl) {
        var ids = idUrl.split('/');
        userInfo = { id: ids.pop(), organizationId: ids.pop(), url: idUrl };
      }
      return {
        accessToken: localStorage.getItem(this._prefix + '_access_token'),
        instanceUrl: localStorage.getItem(this._prefix + '_instance_url'),
        userInfo: userInfo
      };
    }
  }
  return null;
};
```

**Comment by alekhyaAppsbrew** [comment]
I changed the scope and scope configured in SFDC on my  connected app,I still am not able to access refresh token,but when I use jsforce.OAuth2 method instead of jsforce.browser,I can access refresh token,please guide me on the same.

**Comment by ChandanShankar** [comment]
@alekhyaAppsbrew,  Try without passing scope
oauth2.getAuthorizationUrl();
For more details, [here](https://github.com/jsforce/jsforce/issues/242
)

**Comment by siddharatha** [comment]
The refresh token will not be available in a user agent flow.
If you choose the documentation on https://developer.salesforce.com/page/Digging_Deeper_into_OAuth_2.0_on_Force.com

Under the section 
Obtaining an Access Token in a Browser or Native Application (User-Agent Flow)

refresh_token	A long-lived token that may be used to obtain a fresh access token on expiry of the access token in this response. See Token Refresh for more details. Note that refresh_token is only sent if either of the following is the case:
The redirect URI has a custom (non-https) scheme
The redirect URL is exactly https://login.salesforce.com/services/oauth2/success, or on Force.com Sandbox, https://test.salesforce.com/services/oauth2/success.

You will only get a access token in all other cases

**Comment by simmondsty** [comment]
@siddharatha Does that mean you need not worry about refreshing the access token if you are not using one of the exempt cases?

Cases you indicated:
The redirect URI has a custom (non-https) scheme
The redirect URL is exactly https://login.salesforce.com/services/oauth2/success, or on Force.com Sandbox, https://test.salesforce.com/services/oauth2/success.
