### ISSUE TITLE
Can i run directly  SOQL using JSforce in Angular SPA?

### ISSUE THREAD

**Issue by vimehta** [jsforce/jsforce#643]
I am new to salesforce.

Currently, I am using Visual force remoting for CRUD in Angular App.

But it doesn't support fetching relationship data  by doing INNER join on multiple objects. For that I have override the existing method.

So I want to know here can i use directly Inner SOQL query in Angular app, is it good practice to directly write query  ?

**Comment by paustint** [comment]
I am not sure this question is 100% appropriate for posting here, as it is a general support question, but I am happy to help.

> Currently, I am using Visual force remoting for CRUD in Angular App.
But it doesn't support fetching relationship data by doing INNER join on multiple objects. For that I have override the existing method.

Visualforce remoting uses an Apex controller so it does support any SOQL syntax available on the platform and will support the exact same syntax as JSForce would support. If you are talking about `Visualforce Remote Objects`, these do not use an Apex controller and do not support relationship queries.  Can you confirm which you are using?

https://developer.salesforce.com/docs/atlas.en-us.pages.meta/pages/pages_remote_objects.htm
**Versus**
https://developer.salesforce.com/docs/atlas.en-us.pages.meta/pages/pages_js_remoting.htm

JSForce DOES allow relationship queries - as documented here: https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_relationships_query_using.htm#sforce_api_calls_soql_relationships_query_using

Here is an example of a query that would work with VFR and JSForce (or generally any place SOQL is allowed)
```sql
SELECT Id, Name, RecordTypeId, Type, Owner.FirstName, Owner.Id, Owner.LastName, Owner.Name, Owner.Username, 
	(SELECT Id, BillingStreet, CurrencyIsoCode, EndDate, OwnerExpirationNotice, StartDate, Status FROM Contracts), 
	(SELECT Id, Body, IsPrivate, Title FROM Notes), 
	(SELECT Id, Name, FirstName, LastName FROM Contacts)
FROM Account
```

> So I want to know here can i use directly Inner SOQL query in Angular app, is it good practice to directly write query ?

Does the above answer your question?  In general, it IS a good idea to use subqueries to get related child data because you will not need to query additional data.  If you include specifics about your use-case I would be happy to give you additional tips on how to solve.

**Comment by vimehta** [comment]
Thanks a lot for quick response.

I am using below visual force remoting concept - Apex remoting objects
https://developer.salesforce.com/docs/atlas.en-us.pages.meta/pages/pages_remote_objects.htm

You mean directly write SOQL in Javascript using JSforce for fetching relationship at client side?

**Comment by paustint** [comment]
> You mean directly write SOQL in Javascript using JSforce for fetching relationship at client side?

Yes. You can make an API call using JSForce from the browser, back to Salesforce. - https://jsforce.github.io/start/#visualforce

If your application is simple and you only need a couple different queries, then you might consider using Visualforce Remoting instead. Here is a simple example: (note, my queries are using dynamic SOQL to work in orgs without multi-currency, so you would not need to use Database but could use native SOQL queries)

Javascript function (notice "Visualforce" object added to global window object because it was mentioned as the controller)
```html
<apex:page showHeader="false" standardStylesheets="false" sidebar="false" applyHtmlTag="false" applyBodyTag="false" docType="html-5.0" controller="BlockPricingModalRemoter">

<html xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" lang="en">
<head>
  <meta charset="utf-8" />
  <meta http-equiv="x-ua-compatible" content="ie=edge" />
  <title>Block Pricing Modal</title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  <!-- Import the Design System style sheet -->
  <apex:slds />
</head>
    
<body>
CODE HERE
<script type="text/javascript">
    Visualforce.remoting.Manager.invokeAction(
      '{!$RemoteAction.BlockPricingModalRemoter.getBlockPrices}',
      quoteLineId,
      isMultiCurrency,
      function(result, event) {
        console.log('result', result);
        console.log('event', event);
        if(!event.status) { return cb(event.message, result); }
        cb(null, result);
      });
</script>
    
    
</body>
</html>
</apex:page>

```

```java
global class BlockPricingModalRemoter {

    private static String getEscapedString(String str) {
    	return '\'' + str + '\'';
    }

    private static String getQuoteLineQuery(Id quoteLineId, Boolean isMultiCurrency) {
    	String quoteLineQuery = 'SELECT Id, SBQQ__Product__c, SBQQ__Quote__c, SBQQ__Quote__r.Id, SBQQ__Quote__r.SBQQ__PriceBook__c, SBQQ__Quote__r.SBQQ__PricebookId__c';
    	if(isMultiCurrency) { quoteLineQuery += ', CurrencyIsoCode'; }
    	quoteLineQuery += ' FROM SBQQ__QuoteLine__c WHERE Id = ' + getEscapedString(quoteLineId);
    	System.debug('quoteLineQuery: ' + quoteLineQuery);
    	return quoteLineQuery;
    }

    private static String getBlockPricingQuery(Id productId, Id pricebookId, String currencyIsoCode) {
    	String blockPricingQuery = 'SELECT Id, Name, OwnerId, SBQQ__EffectiveDate__c, SBQQ__LowerBound__c, SBQQ__OrderProduct__c, SBQQ__OriginalBlockPrice__c, SBQQ__PriceBook2__c, SBQQ__Price__c, SBQQ__Product__c, SBQQ__QuoteLine__c, SBQQ__UpperBound__c';
    	if(currencyIsoCode != null) { blockPricingQuery += ', CurrencyIsoCode'; }
    	blockPricingQuery += ' FROM SBQQ__BlockPrice__c WHERE  SBQQ__Product__c = ' + getEscapedString(productId) + ' AND  SBQQ__PriceBook2__c = ' + getEscapedString(pricebookId);
    	if(currencyIsoCode != null) { blockPricingQuery += ' AND CurrencyIsoCode = ' + getEscapedString(currencyIsoCode); }
    	blockPricingQuery += ' ORDER BY SBQQ__LowerBound__c DESC';
    	System.debug('blockPricingQuery: ' + blockPricingQuery);
    	return blockPricingQuery;
    }

    @RemoteAction
    global static List<SBQQ__BlockPrice__c> getBlockPrices(Id quoteLineId, Boolean isMultiCurrency) {
    	/** Query quote lines */
    	SObject quoteLine = Database.query(getQuoteLineQuery(quoteLineId, isMultiCurrency));
    	Id productId = (Id)quoteLine.get('SBQQ__Product__c');
    	Id pricebookId = (Id)quoteLine.getSObject('SBQQ__Quote__r').get('SBQQ__PriceBook__c');
    	String currencyIsoCode;
    	if(isMultiCurrency) currencyIsoCode = (String)quoteLine.get('currencyIsoCode');
    	/** Query Block Prices */
    	List<SBQQ__BlockPrice__c> blockPrices = (List<SBQQ__BlockPrice__c>)Database.query(getBlockPricingQuery(productId, pricebookId, currencyIsoCode));

        return blockPrices;
    }

}
```



If you want to use JSForce then you need to create a static resource to host the library or include in your angular app:
```
<apex:page docType="html-5.0" showHeader="false">
  <apex:includeScript value="{!URLFOR($Resource.JSforce)}" />
  <script>
var conn = new jsforce.Connection({ accessToken: '{!$API.Session_Id}' });
conn.query('SELECT Id, Name FROM Account', function(err, res) {
  if (err) { return handleError(err); }
  handleResult(res);
});

// ...

  </script>

</apex:page>
```

**Comment by vimehta** [comment]
I checked **remote object code you have specified controller name** but in my case i am building SPA.  I have mention all salesforce objects for apex remoting in on VF page. So i have  to developed **one global controller** which have  all  custom retrieve methods(will have complex SOQL queries) for all objects. I hope one global class for all custom objects (Currently 25 objects) is fine to do this way in salesforce ?

I think JSForce is better, Is there any limitation using JSforce i mean API call limits?

**Comment by paustint** [comment]
> I think JSForce is better, Is there any limitation using JSforce i mean API call limits?

Just standard salesforce API limits - this defaults to 15000 per day per user, but could be more depending on the salesforce edition and licenses.
https://developer.salesforce.com/docs/atlas.en-us.salesforce_app_limits_cheatsheet.meta/salesforce_app_limits_cheatsheet/salesforce_app_limits_platform_api.htm

Base on your use-case, I would encourage you to use JSForce.  Create an Angular service that manages all the api calls to JSForce - you probably do not want to interact with the library directly in your controllers.  You might even want to setup multiple services, one that manages the api calls, and another that has all the queries and depends on service 1 to actually callout to the package.

Happy to do code/design review if you need to, I am an Angular developer and have used JSForce in my app extensively - but it is standalone webapp, not hosted on the SFDC platform.  you can email me paustint@gmail.com if you want to.

Thanks

**Comment by Absolutestunna** [comment]
Hey @paustint I have a question in regards to using JSForce and a third-party library like Angular or React in my case.  I want to use JSForce in my React app and then upload that React bundle as a static file within a aura component. Based on your experience, will that work? Super new to Salesforce..

**Comment by vimehta** [comment]
Hi,

I have almost done the same thing in Salesforce classic. I loaded angular app inside Visual force Page through the static file.It works fine but you can leverage salesforce inbuilt UI features in this app as you have developed your custom app on top of salesforce.

Just googled might be useful for u
https://www.youtube.com/watch?v=NdnkFjo4O98

Please let me know if u need any more details

**Comment by paustint** [comment]
I have had success bundling a REACT application in a visualforce page.  I have included some code samples that will hopefully get you started

1. You can mock all the data services and run 100% locally first and only deploy to SFDC when ready.
1. I had success using visualforce remoting instead of JSForce if you can, because you can house some logic in Apex as needed, which could be easier to interact with in some cases.  You could use JSForce, but it might be easier to use Apex visualforce remoting and have some basic business logic there if needed.
1. When done, copy the bundled JS as a static resource to salesforce.

There was a blog entry somewhere that talked about developing react react locally with mocked data, but I do not have the link to the article :(

Here is my sanitized code to give you some ideas of what I did, with great success.

### Visualforce page
Only used on SFDC - not local development
```html
<apex:page showHeader="false" standardStylesheets="false" sidebar="false" applyHtmlTag="false" applyBodyTag="false" docType="html-5.0" controller="AssociateVideosRemoteActions">    

  <html xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">    

    <head>
      <title>Some page titel</title>
      <apex:stylesheet value="{!$Resource.SomeCSSAsset}"/>
      <apex:stylesheet value="{!URLFOR($Resource.SLDS221, 'assets/styles/salesforce-lightning-design-system-vf.css')}" />
      <apex:includeScript value="{!$Resource.SomeReactApp}" />
    </head>    

    <body>
      <div id="react"></div>
        <script>
        window.onload = function() {
          console.log(this);
          reactApp.init(document.getElementById('react'));
        };
        </script>
    </body>
  </html>
</apex:page>
```

### HTML Page
Only used for local dev, This allows us to inject mock.js which we mock out our VF Remoting methods by injecting our mock dependency and adding global variables the same way VFR does.
```html
<html>

  <head>
    <link href="resource/SLDS221/assets/styles/salesforce-lightning-design-system.css" rel="stylesheet" type="text/css">
    <link href="resource/SomeCSSAsset.css" rel="stylesheet" type="text/css">
  </head>

  <body>
    <div id="react"></div>
    <script src="build/app.bundle.js"></script>
    <script src="mock.js"></script>
  </body>

</html>
```
### mock.js
This is the mock data service to allow running locally - implement all methods from VF Remoting methods
```javascript
/** Have a bunch of mocked data */
var mockData = [
    {name: 'foo'},
    {name: 'bar'}
];

// Mock data service for SFDC
/** Mthods and parameters and returned data should be based on what SFDC vf remoting would return */
var NameOfVFRemotingClass = {
    someMethodName: (foo, bar, callback) => {
        console.log(this);
        callback(mockData, { status: true });
    },
    someOtherMethodName: (foo, bar, callback) => {
        console.log(this);
        callback(mockData1, { status: true });
    },
};

reactApp.init(document.getElementById('react'));
```
### Main Application
```javascript
import React from 'react';
import { render } from 'react-dom';
...
import { 
    someMethodName,
    someOtherMethodName
} from './services/SalesforceDataService';
/**
 * Initialization function
 * 
 * This is called from the Visualforce Page (or index.html) to initialize the service
 * This function parses out the query string and initializes the data service to pass
 * to the App component
 */
export var init = function(el) {
    // Parse parameters from query string
    let params = {};
    window.location.search.substring(1).split('&').forEach(currVar => {
        var kv = currVar.split('=');
        params[kv[0]] = kv[1];
    });
    // console.log('params', params);
    const dataService = {
        someMethodName: someMethodName,
        someOtherMethodName: someOtherMethodName,
    };
    render((
        <div>
            <App service={dataService} queryParams={params}/>
        </div>
    ), el);
};



/**
 * Main application that is the component that stores the master state of videos
 * and passes down to all child components.
 * 
 * The dataService is passed in as a prop and all data query will happen in this component
 * and state changes will flow up to this component to call methods here to maintain data access consistency
 * for this small application
 */
class App extends React.Component {
    constructor(props) {
        super(props);

        /** Method bindings */
        this.someMethod = this.someMethod.bind(this);
    }

    // Maybe use fat arrow to avoid data binding
    someMethod(content) {
        // Do some stuff here, maybe update state etc..
        // access mock data if needed
    }

    render() {
        return (
            <div className="foo">
               Bar
            </div>
        );
    }

}
```

## Salesforce data service
```javascript
export function someMethodName(foo, bar) {
    return new Promise((resolve, reject) => {
        if(!NameOfVFRemotingClass) { reject({message: 'NameOfVFRemotingClass is not initialized'}); }
        // Should be in global namespace from SFDC
        AssociateVideosRemoteActions.someMethodName(foo, bar, (result, event) => {
            if(!event.status) return reject(event);
            resolve(result);
        });
    });
}

export function someOtherMethodName(foo, bar) {
    return new Promise((resolve, reject) => {
        if(!NameOfVFRemotingClass) { reject({message: 'NameOfVFRemotingClass is not initialized'}); }
        // Should be in global namespace from SFDC
        NameOfVFRemotingClass.someOtherMethodName(foo, bar, (result, event) => {
            if(!event.status) return reject(event);
            resolve(result);
        });
    });
}
```

Example webpack config
```javascript
var path = require('path');
var webpack = require('webpack');

module.exports = {
    output: {
        path: path.resolve(__dirname, 'build'),
        publicPath: '/build',
        filename: 'app.bundle.js'
    },
    devtool: 'source-map',
    entry: {
        app: ['./js/app.js']
    },
    module: {
        loaders: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                loader: 'babel-loader',
                query: {
                    presets: ['es2015', 'react']
                }
            },
            {
                test: require.resolve('./js/app'),
                loaders: ['expose-loader?reactApp', 'babel-loader?presets[]=react,presets[]=es2015']
            }
        ]
    },
    plugins: [
    new webpack.DefinePlugin({
        'process.env': {
            'NODE_ENV': JSON.stringify('production')
        }
    }),
    new webpack.optimize.UglifyJsPlugin(),
    ],
    stats: {
        colors: true
    }
};
```

**Comment by paustint** [comment]
@Absolutestunna - I just re-read your message and saw that you are using lightning - I appologize, my example was for using regular VFP, which you can still do in lightning, but you might also look into the lightning container component, which creates an i-frame for your REACT application. 

I have not done this, so I am not sure what it looks like to add in JSForce in this case and I don't know if visualforce remoting is  supported or not in this case.

https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/aura_compref_lightning_container.htm
