### ISSUE TITLE
Multiple Record Creation under CRUD operation - Record creation limit

### ISSUE THREAD

**Issue by apasrini** [jsforce/jsforce#715]
Wanted to know with jsforce how many records can be created? I am following the same code as in below link under // Multiple records creation

https://jsforce.github.io/document/#create

**Comment by stomita** [comment]
We set the limit of records to create one time to 10 by default, which can be changed in `maxRequest` option in connection, but I don’t recommend to set it to large num because it actually spends a API call per record.
This is due to the current REST API limitation, which only allows single record per request. Composite request in Spring 18 might solve this (but still in dev preview).
