### ISSUE TITLE
Apex is not available on connection

### ISSUE THREAD

**Issue by borys-kupar** [jsforce/jsforce#807]
Hi!
The documentation says that Apex REST api is available on connection object - https://jsforce.github.io/document/#apex-rest

But it's commented out in the code..
https://github.com/jsforce/jsforce/blob/8362b14bd88afe71da0b2c8cdc8a0ea370d987a1/lib/connection.js#L138

Also, It seems to be not exported from the package, so it's not possible to use it directly.
So what is preferred way of calling custom Apex endpoints with jsforce?

Is it not supported at the moment? Can i help somehow on this issue?

**Comment by stomita** [comment]
Apex, soap, bulk, or other extensions are not instantiated directly from `connection.js`. This is because to reduce the footprint size of the core library. If you want to load the library without them, require `jsforce/core` or load `jsforce-core.js` script file in browser, and require `jsforce/lib/api/{apex|soap|bulk}` or load `jsforce-api-{apex|soap|bulk}.js`.

```javascript
var jsforce = require('jsforce/core');
require('jsforce/lib/api/apex');

var jsforce = require('jsforce');
var conn = new jsforce.Connection();

console.log(conn.apex); // available
console.log(conn.bulk); // not available
```

These extensions will automatically be included when you required `jsforce`  or loaded `jsforce.js` bundled file.

```javascript
var jsforce = require('jsforce');
var conn = new jsforce.Connection();

console.log(conn.apex); // available
console.log(conn.bulk); // available
```

**Comment by borys-kupar** [comment]
Thanks for the hint. I am using TypeScript, and I just realised that the problem is in type definitions file (`"@types/jsforce": "1.8.16"`), where declaration for apex is missing.
 
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jsforce/index.d.ts
