### ISSUE TITLE
ListMetadata for ChildXML Names for Custom Object Returning undefined

### ISSUE THREAD

**Issue by dmgerow** [jsforce/jsforce#841]
I am looking to use jsforce to list all metadata components for a specific type. It works for all metadata types returned from the DescribeMetadata Call, but not for the children components (ie: CustomField).

For example, the console.log returns null even when I have many custom fields in my org:

```var types = [{type: 'CustomField', folder: null}];
conn.metadata.list(types, '39.0', function(err, metadata) {
  if (err) { return console.error('err', err); }
    console.log(metadata);
});
```

Am I doing something wrong?

**Comment by paustint** [comment]
@dmgerow - can you try to omit the `folder` property completely?
```javascript
conn.metadata.list([{ type: 'CustomField' }], '42.0', (err, metadata) => {
  if (err) {
    return reject(err);
  }
  resolve(metadata);
});
```

Also, for any types that are in a folder (e.x. reports), it is really dumb, but you must remove "Folder" from the name, except for "EmailFolder" which has a full name of "EmailTemplate".


**Here is what I did when I needed to get parent and child types:**
_Note: this code has been slightly modified, but I am successfully able to get ALL types from describe including all child items and items in folders_
1. call `listMetadata` for the parent type `[{ type: 'CustomField' }]` - no folder property
2. Make sure the response is actually something, because sometimes undefined is returned and if there is only one return item it is an object instead of an array.
```javascript
response = _.isUndefined(response) ? [] : response;
response = !Array.isArray(response) ? [response] : response;
```
3. Then I loop through the responses to get the child items - BUT special processing is needed.
    - If `Folder` is in the type name, you need to remove `Folder`
    - If the type is `EmailFolder` then the fullName is `EmailTemplate`
    - The FullName from the child item is the folder name
```javascript
const type = existingParentType
    .replace('EmailFolder', 'EmailTemplate') // special case with salesforce inconsistent naming
    .replace('Folder', '');
const folder = res.fullName;
conn.metadata.list([{type, folder}], '42.0', (err, childResponse) => { /* handle me */ });
```
Then I used lodash to flatten everything for me if needed because the return types were not always consistent.
```javascript
const output = [];
if (Array.isArray(childResponse)) {
  const output = [];
  output.push(..._.flattenDeep(childResponse));
} else if (_.isObject(childResponse)) {
  output.push(childResponse);
}
```

**Comment by dmgerow** [comment]
This is very helpful - thank you @paustint !
