### ISSUE TITLE
rest backend - staying authenticated with SF ?

### ISSUE THREAD

**Issue by walshe-boylesoftware** [jsforce/jsforce#849]
Hi.. I am using jsforce with username, password and token in my backend rest api.

`const conn = this._conn = new jsforce.Connection({
        loginUrl : this.url
      });`

and then 

`conn.login(config.username, `${config.password}${config.token}`)`

Obviously I do not want to do a conn.login every time my api is invoked, so I use the 'userinfo' obj returned by .login to check if I am already authenticated for future sf calls.

I don't trust this though, surely under the hood the access token expires at some stage.. 
Whats the proper approach here ?

**Comment by KeKs0r** [comment]
After the login your conn object receives the Access Token. You should return the token to the user. The client should store it in something like a cookie or localStorage and then subsequent request don't need to login, but only reuse the provided token.

**Comment by lms15** [comment]
OK  but not ready to login in the children are still with me at this time. I have to wait until
They are out of my home in order to study GitHub. Is it necessary to login at this this time?
If so please let me know
Mamie

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by cristiand391** [comment]
triaging old issues...

for these cases it's probably better to use OAuth and either query Salesforce in your backend or send the access token to the client and let jsforce handle token refresh.

https://jsforce.github.io/document/#access-token-with-refresh-token
