### ISSUE TITLE
Inconsistent fields in response (id vs. Id)

### ISSUE THREAD

**Issue by EricNetsch** [jsforce/jsforce#875]
Pretty minor issues but caused me some issues today that could have been avoided by consistent responses from jsforce. While doing basic CRUD operations sometimes the response has a field `id` and others have the field `Id`. This was pretty unexpected and possibly an easy fix in the package.

Example below:
`salesForce.sobject("Opportunity").create(opportunity);`
Return:
`{ id: '0061U000007gcS7QAI', success: true, errors: [] }`

While:
`salesForce.sobject("Opportunity")
        .findOne(
            {AccountId: accountId},
            {Id: 1}
        ).execute()`

Returns : 
` {"attributes":{"type":"Opportunity","url":"/services/data/v42.0/sobjects/Opportunity/0061U000007gc4KQAQ"},"Id":"0061U000007gc4KQAQ"}`

**Comment by lms15** [comment]
Hello I was studying in code camp to get better knowledge of what and how to
What you are sending me, I am unsure what to do and I still do not see atom on my computer. I need to figure out what I have done wrong why it is not loading
It just not on my desktop yet  nor
the screen to code in. I did get the visual instruction but no scree to type in
Thank you for helping me and it difficult because I do not know java or the codes
Mamie
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by lms15** [comment]
Hello have to stop now eyes hurt and thanks for trying to help me
Mamie

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by gregorskii** [comment]
+1 I see this issue also, the Id field is inconsistently returned.

**Comment by stomita** [comment]
This is from the response schema of the API. The SaveResult includes `id`, and the query result record includes `Id` in Salesforce.

**Comment by stomita** [comment]
In Salesforce it is general for standard fields to be named in CamelCase with first character in Upper case. As the SaveResult is not a record, its properties are named with first character in lower case, which is consistent in almost all REST API in Salesforce.
