### ISSUE TITLE
conn.apex.post - does not get all records back

### ISSUE THREAD

**Issue by jinlii** [jsforce/jsforce#879]
Hi is there a way to retrieve all data back? I don't see a done or nextRecordsUrl field in the response.

Thanks for any help on this in advance!

**Comment by paustint** [comment]
_I am making assumptions because there is very limited information in the ticket._

`done`and `nextRecordsUrl` are only supported through the rest query API (`conn.query`) and are not supported when calling a custom REST Apex endpoint.

Whatever you happen to return in your custom apex method will be what is returned - this should include all records.

For example, I have about 54K accounts in my org and I built a quick test to be sure that all were returned and used the web console to test - https://jsforce.github.io/jsforce-web-console/
```java
@RestResource(urlMapping='/testQueryLocator/*')
global class PostTest {
    @HttpPost
    global static List<Account> getAccounts() {
        return [SELECT Id FROM Account];
    }
}
```
![image](https://user-images.githubusercontent.com/5461649/56778183-4f9baf80-6792-11e9-85f3-b41edda56962.png)

**As you can see, ALL records are returned without pagination. When `conn.query` is used with the same query, we can see only 2000 records are returned and we have the query locator information - which proves that custom APEX endpoints do not paginate the records at all**

![image](https://user-images.githubusercontent.com/5461649/56778257-a2756700-6792-11e9-8bdd-18d63b0ecc4e.png)

**Comment by lms15** [comment]
Hello Jinlii, I have to stop now, I have some family issues and cannot continue
Right now. Thanks for all your assistance
Mamie

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by jinlii** [comment]
Hi @paustint thanks for your explanations! I think I will stick with conn.query. @lms15 I'm a bit confused about your comment. I'm closing this issue.
