### ISSUE TITLE
Default client_id - question

### ISSUE THREAD

**Issue by kai-wang** [jsforce/jsforce#894]
Hi there,

I see the cli authorisation uses the client id in configuration file https://jsforce.github.io/client-config/default.json as default. My question is that where this default client id is sourced from? Normally the client id should be generated from the connected app, which should vary with environment. How does this default client id work for environment?

Thanks,

**Comment by paustint** [comment]
A connected app is created in an org, but once created the app can be used with ANY org across the entirety of Salesforce, assuming that a given org is not configured to block the connected app.

You do not need a connected app per Salesforce environment, but rather you need a connected app per application (because you have to specify the callback URL).

For example:
My web application is not hosted on Salesforce, and has one connected app - and there have been hundreds of different Salesforce orgs that have used my application and have connected using my one connected app.  This is how the OAuth2 protocol is designed - the security model is that you do not have to expose your username and password to me directly, but my application can still make authenticated requests on your behalf into your org.

**Comment by kai-wang** [comment]
Hi Austin, thanks so much for your detailed explanation.

**Comment by lms15** [comment]
Thank you I did not know how to fix it have not had a chance to study yet
Mamie

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
