### ISSUE TITLE
Support to include Datebased filtering (LastModifiedDate)

### ISSUE THREAD

**Issue by kaulonline** [jsforce/jsforce#928]
Hi there,

Thank you for putting this wonderful solution to help the community. I was wondering while pulling the metadata, would there be a possibility to do a check on the lastModifiedDate and pull only those selected components which fall under a certain date range. 

It will not only limit the contents and will only get what all is needed but will also be beneficial to track changes from an auditing perspective.

Any leads would really be helpful for leveraging the JSForce solution.

Kindly suggest

**Comment by cristiand391** [comment]
related: https://github.com/jsforce/jsforce/discussions/1443

docs says `If-Modified-Since` supports sObject Rows, sObject Describe, Describe Global, and Invocable Actions resources.

https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_rest_conditional_requests.htm?q=If-Modified-Since

I'm going to close this in favor of https://github.com/jsforce/jsforce/discussions/1443
