### ISSUE TITLE
Unable to make SalesForce REST API call using jsforce

### ISSUE THREAD

**Issue by salahsaleh** [jsforce/jsforce#980]
I am new to SalesForce and Heroku platform. I am trying to explore and learn as much as possible.

I have developed React app and deployed to Heroku. Its working as expected, but I am at a stage where I am suppose to make Rest API call to Salesforce and get data from SalesForce Object.

I tried jsforce, nforce plugins to connect to Salesforce and fetch data. But unable to.

I used Postman to connect to SalesForce, I am able to connect. But I am getting error when I am trying to connect to Salesforce through code stating (400 bad request).

I have enable CORS on my environment (sandbox). Please let me know if I am missing some configuration settings, it will be really helpful.

var conn = new jsforce.Connection({
      // you can change loginUrl to connect to sandbox or prerelease env.
      loginUrl: "https://test.salesforce.com/"
    });
    conn.login(
      **_userName_**,
      **_password+Token_**,
      function(err, userInfo) {
        if (err) {
          return console.error(err);
        }
        // Now you can get the access token and instance URL information.
        // Save them to establish connection next time.
        console.log(conn.accessToken);
        console.log(conn.instanceUrl);
        // logged in user property
        console.log("User ID: " + userInfo.id);
        console.log("Org ID: " + userInfo.organizationId);
        // ...
      }
    );

And below is the error which I am getting:

<img width="876" alt="herokuIssue" src="https://user-images.githubusercontent.com/6734481/72350116-c6bffd80-36ab-11ea-8966-1c48dbdd062d.PNG">

**Comment by paustint** [comment]
You will want to research about CORS to understand how that works. Basically browsers can only connect directly to servers that add a header that specifically say your site is allowed to connect to it (or whitelist all sites).

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

Salesforce, along with almost every other server, do not allow all origins.

To solve this problem you need to do one of the following:
1. deploy your own server along with your react app so that your app connects to your server, then your server connects to Salesforce.
2. You need to use a proxy server as mentioned in the docs, this would be a second heroku app that would only be used to forward your requests on the Salesforce and send you the results.
    - Docs: https://jsforce.github.io/start/
    - Proxy server: https://github.com/jsforce/jsforce-ajax-proxy

Also - you can probably search through closed issues on this repo and find lots of additional information from prior conversations.

**Comment by sorinstanila** [comment]
Hi,
Have you added your Heroku URL in the **Remote Sites** section in Salesforce?
