### ISSUE TITLE
Using jsforce with Heroku and the nightly reboots

### ISSUE THREAD

**Issue by dan-lutd** [jsforce/jsforce#993]
I have built a test app with jsforce on local dev and pushed to Heroku development server.
On both I can authorize `OAUTH2` via a web browser and put the 
conn.instanceUrl and conn.accessToken  into process.env and access them later.

How can I get that to authorize on startup or reboot?
What I don't see is how we handle the reboot/restart Heroku performs about every 24 hr.

`    import jsforce from 'jsforce'
    import axios from 'axios'
    import express from 'express'
    const router = express.Router();

    const oauth2 = new jsforce.OAuth2({
        loginUrl : process.env.SALESFORCE_URL,
        clientId : process.env.SALESFORCE_KEY,
        clientSecret: process.env.SALESFORCE_SECRET,
        redirectUri: process.env.SALESFORCE_REDIRECT_URI
    });

    // const authUrl = oauth2.getAuthorizationUrl({})
    // console.log(authUrl)
    // axios.get( authUrl )
    // .then(function(res) {
    //     // console.log(res)
    //     // res.redirect(oauth2.getAuthorizationUrl({})); 
    // })

    router.get('/oauth2/auth', oauth2auth )
    router.get('/getAccessToken', getAccesstoken ) 

    router.get('/usersfinfo', userSfInfo) 

    function oauth2auth(req, res) {
        res.redirect(oauth2.getAuthorizationUrl({})); 
    }

    function getAccesstoken(req,res) {
        const conn = new jsforce.Connection({ 
            oauth2 : oauth2
        });
        conn.authorize(req.query.code, function(err, userInfo) {
            if (err) {
                return console.error(err);
            }
            process.env['instanceUrl'] = conn.instanceUrl ;
            process.env['accessToken'] = conn.accessToken ;
            const conn2 = new jsforce.Connection({
                instanceUrl : conn.instanceUrl,
                accessToken : conn.accessToken
            });
            
            
            conn2.identity(function(err, res) {
                if (err) { return console.error(err); }
                console.log("user ID: " + res.user_id);
                console.log("organization ID: " + res.organization_id);
                console.log("username: " + res.username);
                console.log("display name: " + res.display_name);
            });
            res.send("End get Access Token!");     
        });
    }

    function userSfInfo(req, res) {
        if (process.env.instanceUrl ) {
            const conn22 = new jsforce.Connection({
                instanceUrl : process.env.instanceUrl,
                accessToken : process.env.accessToken 
            });

            console.log(process.env.instanceUrl)
            console.log(process.env.accessToken)
            // console.log(conn22)
            conn22.identity(function(err, res) {
                if (err) { return console.error(err); }
                console.log("user ID: " + res.user_id);
                console.log("organization ID: " + res.organization_id);
                console.log("username: " + res.username);
                console.log("display name: " + res.display_name);
            });
            res.send("User Info End!");  
        } else {
            res.send("User Info No instanceUrl");
        }
    };

    router.get('/success', function(req, res) {
    res.send("Just Success!"); 
    });   

    export default router  `

**Comment by paustint** [comment]
I would recommend using the `username` & `password+security-token` flow for your use-case. IF you do not have a human interacting with the service and the server is operating as only one user 100% of the time, then there is no reason you need to use the OAUth2 redirect flow.  Just store the username and password+token ok Heroku as an environment variable. (Note: token is only needed in some cases based on your IP address whitelist config for your SFDC profile).

Alternatively, you could store your access token somewhere persisted instead of in process.env, which will get wiped out if the process dies.  BUT eventually that token will expire and you will need to get another token, which can be done if you also configure the connected app and scope to include the `refresh_token`.

If you happen to already have a token that is valid, then you can configure JSForce to use it by doing something like this:

```typescript
new jsforce.Connection({
  oauth2: new jsforce.OAuth2({
    loginUrl,
    clientId: process.env.clientId,
    clientSecret: process.env.clientSecret,
    redirectUri: process.env.redirectUri,
  }),
  instanceUrl: authInfo.instanceUrl,
  accessToken: authInfo.accessToken,
  refreshToken: authInfo.refreshToken,
});
```

**Also, there are likely a lot of closed issues in the repo of examples of things related to the authorization and connection to salesforce, you may want to search and read those conversations as they could be useful to you.**

**Comment by dan-lutd** [comment]
I am now successfully connecting with  username & password+security-token flow. 
From what I read the refresh token is not sent with this flow.
